### ISSUE TITLE
.selector:not(*:root) {} is not valid CSS3, but valid CSS Selectors 4

### ISSUE THREAD

**Issue by SelenIT** [4ae9b8/browserhacks#162]
The selector `.selector:not(*:root) {}` is presented as the 'hack' for WebKit and marked as 'valid CSS'. The latter is not the case: CSS Selectors 3 spec [allows only simple selectors](http://www.w3.org/TR/css3-selectors/#negation) (i.e. one type, class, pseudo-class or ID selector) as the argument for `:not()`, so currently it doesn't pass the [W3C CSS validation](https://jigsaw.w3.org/css-validator/#validate_by_input). But CSS Selectors 4 draft [allows selector list](http://dev.w3.org/csswg/selectors/#negation) there, making this selector valid. So it can get supported in other browsers one day, becoming not WebKit hack any more.

I believe that to rely on 'hacks' that are actually partial support of experimental, but possibly standard features, for filtering browsers is a bad idea at all, but marking this particular 'hack' as 'valid CSS' is simply misleading. I believe that this selector should have a brief explanation of what it actually does, why it's currently supported by WebKits only and why you shouldn't rely on it too much.

**Comment by jeffclayton** [comment]
As far as a hack goes, pretty much any hack is not ever assumed to be more than temporary as a fix. Many of them will change as to what browser or browsers they work for. At this time this one only affects Safari and Chrome. It may affect others later, sure. Most likely it will by the CSS4 spec as you pointed out.

Hugo, Tim, etc... the other one I find very curious and a very good point - I ran this through the regular CSS validators and since they are 2.1 and 3.0, just like @SelenIT says-- it does not validate pre-CSS4. Anyone know what validator was used to test this? Or was the CSS4 spec the reason why it was listed as valid since it 'should be' in the future? 

Is there a way (perhaps this would solve SelenIT's concern) to add a note on the HTML validator icon -- to have a number added for when the CSS code actually became valid CSS. To me this would make sense because CSS3 validating code would not validate under 2.1 validation tools, but will under the 3+ ones.

**Comment by HugoGiraudel** [comment]
Unfortunately, I do not have time to work on Browserhacks anymore. PR are welcome but I won't engage new development work by myself unfortunately.

**Comment by jeffclayton** [comment]
Perhaps I can assist?

**Comment by HugoGiraudel** [comment]
Depending on what you want to do and the amount of time you have, perhaps. :)

**Comment by jeffclayton** [comment]
You and I both have IT jobs so you are familiar with my time issues but I do have interest in helping - I would rather email if you could to discuss possibilities. Simplest way to reach me is mailjeffclayton@gmail.com

**Comment by KittyGiraudel** [comment]
The CSS validation feature has been removed.
