### ISSUE TITLE
Moving to Jekyll

### ISSUE THREAD

**Issue by KittyGiraudel** [4ae9b8/browserhacks#174]
I am currently in the process of moving the site to Jekyll in order for it to be hosted on GitHub Pages and easier to manage. I only have a little JS to do and everything should be good.

**Comment by jeffclayton** [comment]
Sounds like a great idea

**Comment by jeffclayton** [comment]
Related question (build-wise) are there any specific application(s) you are using to create the page or all manual? Much of it appears computer generated such as the use of UUIDs to differentiate the hacks, scss tools etc... just curious.

**Comment by KittyGiraudel** [comment]
Once we move to Jekyll, Jekyll + npm scripts should be all.

**Comment by KittyGiraudel** [comment]
Alright, so here it is. The new default branch is the `gh-pages` branch. The `master` branch is now useless. The `old-gh-pages` branch is now useless and just holds the old status on the gh-pages branch. 

Here are a few things that changed:
- The quality of the JavaScript code base has been improved.
- The quality of the SCSS code base has been dramatically improved.
- The templates are now dramatically simpler to understand.
- The no-JavaScript experience is now decent.
- The data for the hacks, types and browsers now live in the `_data` folder.
- Any chance to the `gh-pages` branch (through a push, a direct edit on GitHub or the merge of a PR) now triggers a build, which makes it easy for contributors to, well, contribute.

**Comment by jeffclayton** [comment]
The hacks appear to no longer be working

**Comment by KittyGiraudel** [comment]
Which ones? You have to give me a bit more here Jeff. :)

Le lun. 11 avr. 2016 04:31, Jeff Clayton notifications@github.com a
écrit :

**Comment by jeffclayton** [comment]
It turns out that after you asked that, I went to my office and did a little more testing. It appears to be the windows 10 machine I am testing with (32-bit) running MSIE 11 and Edge -- but I cannot be sure if it is due to 32-bit version of Windows 10 or more likely an issue with the computer itself -- I tested it with a 64-bit bit one and it is okay. 

Other browsers such as Firefox and Chrome on other machines are happy. Safari on the old and new Macs I have access to is fine as well. It could be simply an issue with the computer itself but I do not have a second 32-bit windows 10 box on hand at the moment. Unfortunately since I can't see the previous build (from before this weekend) on the machine I cannot compare before and after either.

For reference, the build version is 10586 [current]. I am not loading the preview builds at the moment, they are not compatible with all of my hardware. While I would not assume a problem after seeing this, it is worth testing on other machines to find out if it is simply a configuration oddity. I can test 32/64 windows 7 with ie11 later just to see if there is something up with that one in any way.

I notice you don't have 'enable tests' by default now, i think the site is more handy if it is already selected. Does it crash if tests enabled on some machines? Just curious.

**Comment by KittyGiraudel** [comment]
> I notice you don't have 'enable tests' by default now, i think the site is more handy if it is already selected. Does it crash if tests enabled on some machines? Just curious.

Just forgot the default was on. I’ll add it back.

**Comment by jeffclayton** [comment]
I tried a windows 7 32-bit box with ie11 and it seems to work. Sometimes it failed to enable tests, but it looks like it simply crashed without messages. For the moment the windows 10 32-bit box is the one that refuses to play ball at all. I hope it is only a configuration glitch on that particular machine.
