### ISSUE TITLE
Is there any css hack specifically for safari 13.1

### ISSUE THREAD

**Issue by karamjeetiron** [4ae9b8/browserhacks#201]
In safari 13.1 Catalina some css properties not working. So for this browser only is there any css hack ? Please let me know if there is the solution to attain this. 

I am using bootstrap 5.3 and its flex gap classes not working in safari 13.1 browser but working on newer browsers. So for this specific browser i need to set these gap classes with margin like following code
```
.flex-gap-4 {
  display: flex;
  flex-wrap: wrap;
  margin-left: -1rem;
  margin-top: -1rem;
}

.flex-gap-4 > * {
  margin-left: 1rem;
  margin-top: 1rem;
}
```

**Comment by karamjeetiron** [comment]
I tried following hack but it not considering 13.1 version. Need Help ...

```
/* Safari 9+, < 13.1 */

@supports (-webkit-marquee-repetition:infinite) and (object-fit:fill) {

    .safari_only { 

        color:#0000FF; 
        background-color:#CCCCCC; 

    }
}
```

**Comment by browserstrangeness** [comment]
Go to the main page at https://browserstrangeness.github.io to see the one I created for Safari 7.1+
It is still working in Safari 16.4 (on Mac OS X Ventura)

The page shows it in red if it works for your browser.

_::-webkit-full-page-media, _:future, :root .safari_only {
        color:#0000FF; 
        background-color:#CCCCCC; 
}

**Comment by browserstrangeness** [comment]
Do note what it says on the other hack you posted:

/* Safari 9+, < 13.1 */

This is correct. 'less than' 13.1 does not include 13.1, as stated.

**Comment by karamjeetiron** [comment]
Thanks for your response. 

The problem is i want solution for  <=13.1 (this browser) and even if it covered older browser including 13.1. I do not want hack for newer browsers(14,15,16)

Let me explain the problem in detail then i think you can relate what exactly i want :

I am using bootstrap 5.3 and its flex gap classes not working in safari 13.1 but works in 14, 15 and 16 browsers browsers(Latest). So for this specific browser i need to set these gap classes with margin. I will override these gap classes with CSS and i will do by giving margin to child elements.

We cannot ignored 13.1 users because even the number is less but we want to give support. Gap classes working fine in all other browsers like chrome , Firefox , edge . I need CSS hack for this particular browser.

I think you guys may have hack for this. I guess.

Thanks

**Comment by jeffclayton** [comment]
Your points of what you can and cannot ignore are fine, as those are actually why we write CSS hacks like this in the first place.

There are actually two ways you can go about that then. 13.1 and less, OR 14.0 and up because CSS goes in order and there were no higher versions of 13.X released. Either would allow you to inject or overwrite with your injected CSS. Neither is written at this time however, but are possible. I (or anyone) would have to find a feature that gets tagged as supported (or not supported) in 14 to make what you want happen. 

On a side note, if you are in a real time-crunch, you can also detect it with Javascript since that can detect specific versions without CSS. You aren't limited.

**Comment by karamjeetiron** [comment]
Thanks for your response @jeffclayton

Yes, it can be possible as you said but now am doing it with JavaScript to detect browser and its version. Its working as i want.

Btw browserhacks truely a gem. I appreciate your work!

Thanks for your suggestions !
